[2025-04-14T05:08:34.820+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-14T05:08:34.834+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.fetch_permits_task manual__2025-04-14T05:08:31.111131+00:00 [queued]>
[2025-04-14T05:08:34.840+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.fetch_permits_task manual__2025-04-14T05:08:31.111131+00:00 [queued]>
[2025-04-14T05:08:34.840+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-14T05:08:34.849+0000] {taskinstance.py:2890} INFO - Executing <Task(BranchPythonOperator): fetch_permits_task> on 2025-04-14 05:08:31.111131+00:00
[2025-04-14T05:08:34.854+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=394) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-14T05:08:34.855+0000] {standard_task_runner.py:72} INFO - Started process 396 to run task
[2025-04-14T05:08:34.856+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'fetch_permits_task', 'manual__2025-04-14T05:08:31.111131+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp4xn4ha0l']
[2025-04-14T05:08:34.856+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask fetch_permits_task
[2025-04-14T05:08:34.887+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.fetch_permits_task manual__2025-04-14T05:08:31.111131+00:00 [running]> on host 8f3f7397b438
[2025-04-14T05:08:34.930+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='fetch_permits_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-14T05:08:31.111131+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-14T05:08:31.111131+00:00'
[2025-04-14T05:08:34.931+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-14T05:08:34.932+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-14T05:08:34.932+0000] {logging_mixin.py:190} INFO - Current task name:fetch_permits_task state:running start_date:2025-04-14 05:08:34.835361+00:00
[2025-04-14T05:08:34.932+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag and current dag run status:running
[2025-04-14T05:08:34.932+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-14T05:08:34.932+0000] {baseoperator.py:423} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-04-14T05:08:34.938+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-04-29 (offset=0)
[2025-04-14T05:08:35.831+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-04-30 (offset=0)
[2025-04-14T05:08:36.145+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-01 (offset=0)
[2025-04-14T05:08:36.494+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-02 (offset=0)
[2025-04-14T05:08:36.768+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-03 (offset=0)
[2025-04-14T05:08:37.128+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-04 (offset=0)
[2025-04-14T05:08:37.520+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-05 (offset=0)
[2025-04-14T05:08:37.896+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-06 (offset=0)
[2025-04-14T05:08:38.231+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-07 (offset=0)
[2025-04-14T05:08:38.561+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-08 (offset=0)
[2025-04-14T05:08:38.890+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-09 (offset=0)
[2025-04-14T05:08:39.223+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-10 (offset=0)
[2025-04-14T05:08:43.218+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-11 (offset=0)
[2025-04-14T05:08:43.649+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-12 (offset=0)
[2025-04-14T05:08:44.005+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-13 (offset=0)
[2025-04-14T05:08:48.777+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-14 (offset=0)
[2025-04-14T05:08:49.178+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-15 (offset=0)
[2025-04-14T05:08:49.512+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-16 (offset=0)
[2025-04-14T05:08:49.823+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-17 (offset=0)
[2025-04-14T05:08:49.957+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-18 (offset=0)
[2025-04-14T05:08:50.256+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-19 (offset=0)
[2025-04-14T05:08:50.598+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-20 (offset=0)
[2025-04-14T05:08:50.915+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-21 (offset=0)
[2025-04-14T05:08:51.304+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-22 (offset=0)
[2025-04-14T05:08:51.689+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-23 (offset=0)
[2025-04-14T05:08:51.990+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-24 (offset=0)
[2025-04-14T05:08:52.143+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-25 (offset=0)
[2025-04-14T05:08:52.452+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-26 (offset=0)
[2025-04-14T05:08:52.836+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-27 (offset=0)
[2025-04-14T05:08:53.196+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-28 (offset=0)
[2025-04-14T05:08:53.589+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-29 (offset=0)
[2025-04-14T05:08:53.980+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-30 (offset=0)
[2025-04-14T05:08:54.284+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-05-31 (offset=0)
[2025-04-14T05:08:54.604+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-01 (offset=0)
[2025-04-14T05:08:54.944+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-02 (offset=0)
[2025-04-14T05:08:55.292+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-03 (offset=0)
[2025-04-14T05:08:55.639+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-04 (offset=0)
[2025-04-14T05:08:55.995+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-05 (offset=0)
[2025-04-14T05:08:59.189+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-06 (offset=0)
[2025-04-14T05:08:59.836+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-07 (offset=0)
[2025-04-14T05:09:00.150+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-08 (offset=0)
[2025-04-14T05:09:00.634+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-09 (offset=0)
[2025-04-14T05:09:00.994+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-10 (offset=0)
[2025-04-14T05:09:01.568+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-11 (offset=0)
[2025-04-14T05:09:01.994+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-12 (offset=0)
[2025-04-14T05:09:02.358+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-13 (offset=0)
[2025-04-14T05:09:02.669+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-14 (offset=0)
[2025-04-14T05:09:02.948+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-15 (offset=0)
[2025-04-14T05:09:03.331+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-16 (offset=0)
[2025-04-14T05:09:03.696+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-17 (offset=0)
[2025-04-14T05:09:04.093+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-18 (offset=0)
[2025-04-14T05:09:04.484+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-19 (offset=0)
[2025-04-14T05:09:04.895+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-20 (offset=0)
[2025-04-14T05:09:05.209+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-21 (offset=0)
[2025-04-14T05:09:05.519+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-22 (offset=0)
[2025-04-14T05:09:05.962+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-23 (offset=0)
[2025-04-14T05:09:08.637+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-24 (offset=0)
[2025-04-14T05:09:09.161+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-25 (offset=0)
[2025-04-14T05:09:09.552+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-26 (offset=0)
[2025-04-14T05:09:10.014+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-27 (offset=0)
[2025-04-14T05:09:10.314+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-28 (offset=0)
[2025-04-14T05:09:10.652+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-29 (offset=0)
[2025-04-14T05:09:11.068+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-06-30 (offset=0)
[2025-04-14T05:09:11.493+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-01 (offset=0)
[2025-04-14T05:09:11.988+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-02 (offset=0)
[2025-04-14T05:09:12.376+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-03 (offset=0)
[2025-04-14T05:09:12.759+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-04 (offset=0)
[2025-04-14T05:09:13.138+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-05 (offset=0)
[2025-04-14T05:09:13.481+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-06 (offset=0)
[2025-04-14T05:09:14.017+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-07 (offset=0)
[2025-04-14T05:09:14.449+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-08 (offset=0)
[2025-04-14T05:09:14.912+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-09 (offset=0)
[2025-04-14T05:09:15.330+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-10 (offset=0)
[2025-04-14T05:09:15.739+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-11 (offset=0)
[2025-04-14T05:09:16.061+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-12 (offset=0)
[2025-04-14T05:09:16.225+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-13 (offset=0)
[2025-04-14T05:09:16.637+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-14 (offset=0)
[2025-04-14T05:09:17.054+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-15 (offset=0)
[2025-04-14T05:09:17.462+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-16 (offset=0)
[2025-04-14T05:09:17.819+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-17 (offset=0)
[2025-04-14T05:09:18.190+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-18 (offset=0)
[2025-04-14T05:09:18.522+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-19 (offset=0)
[2025-04-14T05:09:18.850+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-20 (offset=0)
[2025-04-14T05:09:19.221+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-21 (offset=0)
[2025-04-14T05:09:19.736+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-22 (offset=0)
[2025-04-14T05:09:20.130+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-23 (offset=0)
[2025-04-14T05:09:20.482+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-24 (offset=0)
[2025-04-14T05:09:20.944+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-25 (offset=0)
[2025-04-14T05:09:21.256+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-26 (offset=0)
[2025-04-14T05:09:21.554+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-27 (offset=0)
[2025-04-14T05:09:21.946+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-28 (offset=0)
[2025-04-14T05:09:22.331+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-29 (offset=0)
[2025-04-14T05:09:22.758+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-30 (offset=0)
[2025-04-14T05:09:23.186+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-07-31 (offset=0)
[2025-04-14T05:09:23.588+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-01 (offset=0)
[2025-04-14T05:09:23.934+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-02 (offset=0)
[2025-04-14T05:09:24.255+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-03 (offset=0)
[2025-04-14T05:09:24.679+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-04 (offset=0)
[2025-04-14T05:09:25.038+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-05 (offset=0)
[2025-04-14T05:09:25.415+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-06 (offset=0)
[2025-04-14T05:09:25.812+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-07 (offset=0)
[2025-04-14T05:09:26.205+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-08 (offset=0)
[2025-04-14T05:09:26.501+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-09 (offset=0)
[2025-04-14T05:09:26.873+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-10 (offset=0)
[2025-04-14T05:09:27.274+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-11 (offset=0)
[2025-04-14T05:09:27.744+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-12 (offset=0)
[2025-04-14T05:09:28.139+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-13 (offset=0)
[2025-04-14T05:09:28.561+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-14 (offset=0)
[2025-04-14T05:09:28.960+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-15 (offset=0)
[2025-04-14T05:09:29.305+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-16 (offset=0)
[2025-04-14T05:09:29.656+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-17 (offset=0)
[2025-04-14T05:09:30.070+0000] {logging_mixin.py:190} INFO - Fetching records for 2020-08-18 (offset=0)
[2025-04-14T05:09:40.087+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='data.cityofnewyork.us', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 86, in fetch_permits
    results = client.get(
              ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sodapy/socrata.py", line 412, in get
    response = self._perform_request(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sodapy/socrata.py", line 551, in _perform_request
    response = getattr(self.session, request_type)(uri, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='data.cityofnewyork.us', port=443): Read timed out. (read timeout=10)
[2025-04-14T05:09:40.116+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-14T05:09:40.116+0000] {logging_mixin.py:190} INFO - Task start:2025-04-14 05:08:34.835361+00:00 end:2025-04-14 05:09:40.115758+00:00 duration:65.280397
[2025-04-14T05:09:40.117+0000] {logging_mixin.py:190} INFO - Task:<Task(BranchPythonOperator): fetch_permits_task> dag:<DAG: data_ingestion_gcs_dag> dagrun:<DagRun data_ingestion_gcs_dag @ 2025-04-14 05:08:31.111131+00:00: manual__2025-04-14T05:08:31.111131+00:00, state:running, queued_at: 2025-04-14 05:08:31.121205+00:00. externally triggered: True>
[2025-04-14T05:09:40.117+0000] {logging_mixin.py:190} INFO - Failure caused by HTTPSConnectionPool(host='data.cityofnewyork.us', port=443): Read timed out. (read timeout=10)
[2025-04-14T05:09:40.118+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=fetch_permits_task, run_id=manual__2025-04-14T05:08:31.111131+00:00, execution_date=20250414T050831, start_date=20250414T050834, end_date=20250414T050940
[2025-04-14T05:09:40.198+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-14T05:09:40.199+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task fetch_permits_task (HTTPSConnectionPool(host='data.cityofnewyork.us', port=443): Read timed out. (read timeout=10); 396)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='data.cityofnewyork.us', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 86, in fetch_permits
    results = client.get(
              ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sodapy/socrata.py", line 412, in get
    response = self._perform_request(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sodapy/socrata.py", line 551, in _perform_request
    response = getattr(self.session, request_type)(uri, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='data.cityofnewyork.us', port=443): Read timed out. (read timeout=10)
[2025-04-14T05:09:40.258+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-14T05:09:40.300+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-14T05:09:40.301+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
